version: "3.9"
services:
  database:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: auth
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

