name: Develop - build and push image
on:
  push:
    branches:
      - master
    paths:
      - 'apps/**/src/**'
      - 'libs/**/src/**'
      - '.github/workflows/build-docker.yaml'
jobs:
  setup-build-publish:
    name: Setup, Build, Publish
    runs-on: [ self-hosted ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup NX workspace SHAs
        uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: master

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install Dependencies
        run: yarn

      - uses: nrwl/last-successful-commit-action@v1
        id: last_successful_commit
        with:
          branch: 'master'
          workflow_id: 'build-docker.yml'
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Build affected apps'
        run: yarn nx affected --target=container --base=${{ steps.last_successful_commit.outputs.commit_hash }} --parallel
